GITURL	= http://github.com/wanderlust/flim.git
TAG     = 3584bece012fd780361b17f0e2767c060cb91ff3
NAME	= flim
VERSION	= 1.14.9_20100804
PASDEF	= flim.pasdef
FILES = \
eword-decode.el \
eword-encode.el \
hex-util.el \
hmac-def.el \
hmac-md5.el \
hmac-sha1.el \
luna.el \
lunit.el \
md4.el \
md5-dl.el \
md5.el \
md5-el.el \
mel-b-ccl.el \
mel-b-dl.el \
mel-b-el.el \
mel.el \
mel-g.el \
mel-q-ccl.el \
mel-q.el \
mel-u.el \
mime-conf.el \
mime-def.el \
mime.el \
mime-parse.el \
mmbuffer.el \
mmcooked.el \
mmexternal.el \
mmgeneric.el \
ntlm.el \
qmtp.el \
sasl-cram.el \
sasl-digest.el \
sasl.el \
sasl-ntlm.el \
sasl-scram.el \
sha1-dl.el \
sha1.el \
sha1-el.el \
smtp.el \
std11.el \
FLIM-API.en \
mime-en.texi \
mime-en.sgml \
mime-ja.texi \
ftp.in \
ChangeLog \
README.ja \
mime-ja.sgml \
sasl.texi \
VERSION \
README.en \
NEWS

DESCRIPTION = Package for $NAME ($VERSION).

include ../generic-git.mk
include ../launchpad.mk
