GITURL	= http://github.com/wanderlust/flim.git -b flim-1_14
TAG     = flim-1_14_9
NAME	= flim
VERSION	= 1.14.9
PASDEF	= flim.pasdef
FILES = build/*.el \
build/FLIM-API.en \
build/mime-en.texi \
build/mime-en.sgml \
build/mime-ja.texi \
build/ftp.in \
build/ChangeLog \
build/README.ja \
build/mime-ja.sgml \
build/sasl.texi \
build/VERSION \
build/README.en \
build/NEWS

DESCRIPTION = Package for $NAME ($VERSION).

include ../generic-git.mk
include ../launchpad.mk
