GITURL	= http://github.com/wanderlust/flim.git -b flim-1_14
TAG     = flim-1_14_9
NAME	= flim
VERSION	= 1.14.9
PASDEF	= flim.pasdef
FILES = \
build/eword-decode.el \
build/eword-encode.el \
build/hex-util.el \
build/hmac-def.el \
build/hmac-md5.el \
build/hmac-sha1.el \
build/luna.el \
build/lunit.el \
build/md4.el \
build/md5-dl.el \
build/md5.el \
build/md5-el.el \
build/mel-b-ccl.el \
build/mel-b-dl.el \
build/mel-b-el.el \
build/mel.el \
build/mel-g.el \
build/mel-q-ccl.el \
build/mel-q.el \
build/mel-u.el \
build/mime-conf.el \
build/mime-def.el \
build/mime.el \
build/mime-parse.el \
build/mmbuffer.el \
build/mmcooked.el \
build/mmexternal.el \
build/mmgeneric.el \
build/ntlm.el \
build/qmtp.el \
build/sasl-cram.el \
build/sasl-digest.el \
build/sasl.el \
build/sasl-ntlm.el \
build/sasl-scram.el \
build/sha1-dl.el \
build/sha1.el \
build/sha1-el.el \
build/smtp.el \
build/std11.el \
build/FLIM-API.en \
build/mime-en.texi \
build/mime-en.sgml \
build/mime-ja.texi \
build/ftp.in \
build/ChangeLog \
build/README.ja \
build/mime-ja.sgml \
build/sasl.texi \
build/VERSION \
build/README.en \
build/NEWS

DESCRIPTION = Package for $NAME ($VERSION).

include ../generic-git.mk
include ../launchpad.mk
