URL = http://www.webweavertech.com/ovidiu/emacs/find-recursive.txt
VERSION = 20010326
NAME = find-recursive
PASDEF = find-recursive.pasdef
FILE = find-recursive.el
FETCHFILE = find-recursive.txt

include ../generic-single.mk
include ../generic-e6h.mk
