GITURL		= http://github.com/wanderlust/semi.git
TAG 		= semi-1_14_6
NAME		= semi
VERSION		= 1.14.6
PASDEF		= semi.pasdef
DESCRIPTION	= Package for $NAME ($VERSION).

FILES = build/*.el build/ChangeLog build/README.*

include ../generic-git.mk
include ../launchpad.mk
