GITURL		= http://github.com/wanderlust/semi.git
TAG 		= c44e61ef0b850adac5ed4dc2c46b736946a41c53
NAME		= semi
VERSION		= 1.14.6_20101024
PASDEF		= semi.pasdef
DESCRIPTION	= Package for $NAME ($VERSION).

FILES = \
mail-mime-setup.el \
mime-bbdb.el \
mime-edit.el \
mime-image.el \
mime-partial.el \
mime-pgp.el \
mime-play.el \
mime-setup.el \
mime-view.el \
mime-w3.el \
pgg-def.el \
pgg.el \
pgg-gpg.el \
pgg-parse.el \
pgg-pgp5.el \
pgg-pgp.el \
postpet.el \
semi-def.el \
semi-setup.el \
signature.el \
smime.el \
ChangeLog \
README.*

include ../generic-git.mk
include ../launchpad.mk
