URL		= http://www.kazmier.com/computer/snippet.el
VERSION		= 0.2
NAME		= snippet
PASDEF		= snippet.pasdef
FILE		= snippet.el
FETCHFILE	= snippet.el

include ../generic-single.mk
include ../generic-e6h.mk
