NAME    = google-weather
VERSION = 20101122
GITURL  = git://git.naquadah.org/google-weather-el.git
TAG     = e8c50ad6f41d8e97bde5d26ee176019616abe198
PASDEF  = google-weather.pasdef
FILES   = *.el

include ../generic-git.mk
include ../generic-e6h.mk
