SVNURL = http://lampsvn.epfl.ch/svn-repos/scala/scala-tool-support/tags/R_2_8_0_final/src/emacs/
VERSION = 2.8.0.final
NAME = scala-mode
PASDEF = scala-mode.pasdef
FILES = \
build/*.el \
build/AUTHORS \
build/FUTURE \
build/README \
build/contrib/README \
build/contrib/dot-ctags 

DESCRIPTION = Package for $NAME ($VERSION)

include ../generic-svn.mk
include ../launchpad.mk
