SVNURL		= http://lampsvn.epfl.ch/svn-repos/scala/scala-tool-support/tags/R_2_8_0_final/src/emacs/
VERSION		= 2.8.0.final
NAME		= scala-mode
PASDEF		= scala-mode.pasdef
DESCRIPTION	= Package for $NAME ($VERSION)
FILES		= \
*.el \
AUTHORS \
FUTURE \
README \
contrib/README \
contrib/dot-ctags 

include ../generic-svn.mk
include ../generic-e6h.mk
