URL		= http://orgmode.org/org-7.7.tar.gz
VERSION		= 7.7
NAME		= org-mode
PASESFILE	= $(NAME)-$(VERSION).pases
TARFILE		= org-7.7.tar.gz
PASDEF		= org-mode.pasdef
DESCRIPTION	= Package for org-mode $(VERSION)
FILES		= \
Changes.org \
README \
contrib/README \
contrib/babel/langs/*.el \
contrib/babel/library-of-babel.org \
contrib/lisp/*.el \
contrib/scripts/* \
contrib/scripts/staticmathjax/* \
contrib/scripts/staticmathjax/chrome/* \
contrib/scripts/staticmathjax/chrome/content/* \
contrib/scripts/staticmathjax/defaults/preferences/* \
doc/* \
lisp/*.el \
request-assign-future.txt

include ../generic-targz.mk
include ../generic-e6h.mk
