URL = http://orgmode.org/org-6.02.tar.gz
VERSION = 6.02
NAME = org
PASESFILE = $(NAME)-$(VERSION).pases
TARFILE = org-6.02.tar.gz
PASDEF = org.pasdef
ELFILES = build/lisp/org-publish.el \
build/lisp/org-info.el \
build/lisp/org-bibtex.el \
build/lisp/org-vm.el \
build/lisp/org-wl.el \
build/lisp/org-clock.el \
build/lisp/org-rmail.el \
build/lisp/org-faces.el \
build/lisp/org-macs.el \
build/lisp/org-install.el \
build/lisp/org-archive.el \
build/lisp/org-infojs.el \
build/lisp/org-colview-xemacs.el \
build/lisp/org-colview.el \
build/lisp/org.el \
build/lisp/org-agenda.el \
build/lisp/org-export-latex.el \
build/lisp/org-exp.el \
build/lisp/org-irc.el \
build/lisp/org-gnus.el \
build/lisp/org-compat.el \
build/lisp/org-mew.el \
build/lisp/org-table.el \
build/lisp/org-mhe.el \
build/lisp/org-mouse.el \
build/lisp/org-bbdb.el \
build/lisp/org-remember.el \
build/lisp/org-mac-message.el \
build/xemacs/ps-print-invisible.el \
build/xemacs/noutline.el \
build/CONTRIB/lisp/org-interactive-query.el \
build/CONTRIB/lisp/org-id.el \
build/CONTRIB/lisp/org-elisp-symbol.el \
build/CONTRIB/lisp/org-screen.el \
build/CONTRIB/lisp/org-bookmark.el \
build/CONTRIB/lisp/org-mairix.el \
build/CONTRIB/lisp/org-panel.el \
build/CONTRIB/lisp/org2rem.el \
build/CONTRIB/lisp/org-depend.el \
build/CONTRIB/lisp/org-annotate-file.el \
build/CONTRIB/lisp/org-expiry.el \
build/CONTRIB/lisp/org-man.el \
build/CONTRIB/lisp/org-toc.el \
build/CONTRIB/lisp/org-registry.el \
build/CONTRIB/lisp/orgtbl-sqlinsert.el \
build/CONTRIB/packages/org-export-freemind-0.1.0/org-export-freemind-install.el \
build/CONTRIB/packages/org-export-freemind-0.1.0/org-export-freemind.el

DOCFILES = \
build/doc/dir \
build/doc/org \
build/doc/orgcard.pdf \
build/doc/orgcard.tex \
build/doc/org.pdf \
build/doc/org.info \
build/doc/orgcard_letter.pdf \
build/README \
build/request-assign-future.txt \
build/Changes.org \
build/xemacs/README \
build/ChangeLog \
build/CONTRIB/packages/org-export-freemind-0.1.0/README \
build/CONTRIB/packages/org-export-freemind-0.1.0/ChangeLog \
build/CONTRIB/README \
build/CONTRIB/scripts/dir2org.zsh \
build/CONTRIB/scripts/org2hpda \
build/CONTRIB/ChangeLog

FILES = $(ELFILES) $(DOCFILES) $(PASDEF)

include ../generic-targz.mk
