NAME		= ensime
VERSION		= 0.4.1
URL		= https://github.com/downloads/aemoncannon/ensime/ensime_2.8.1-0.4.1.tar.gz
TARFILE		= ensime_2.8.1-0.4.1.tar.gz
PASDEF		= ensime.pasdef
DESCRIPTION	= Package for $NAME ($VERSION).
PASESFILE	= $(NAME)-$(VERSION).pases
FILES		= \
elisp/ensime*.el \
LICENSE \
README.md \
bin/server.bat \
bin/server.sh \
lib/*.jar

include ../generic-targz.mk
