URL		= http://js2-mode.googlecode.com/files/js2-20090723b.el
VERSION		= 20090723b
NAME		= js2
PASDEF		= js2.pasdef
FILE		= js2.el
FETCHFILE	= js2-20090723b.el
DESCRIPTION	= Package for js2-mode (v. 20090723b)

include ../generic-single.mk
include ../launchpad.mk
