URL = http://cvs.savannah.gnu.org/viewvc/*checkout*/emacs/emacs/lisp/progmodes/flymake.el?revision=1.2.4.41
VERSION = 0.3
NAME = flymake
PASDEF = flymake.pasdef
FILE = flymake.el
FETCHFILE = flymake.el?revision=1.2.4.41

include ../generic-single.mk
include ../generic-e6h.mk
