URL		= http://xahlee.org/emacs/speck.el
VERSION		= 20100525
NAME		= speck
PASDEF		= speck.pasdef
FILE		= speck.el
FETCHFILE	= speck.el
DESCRIPTION	= Package for $(NAME) (v. $(VERSION))

include ../generic-single.mk
include ../generic-e6h.mk
