URL = http://niels.kicks-ass.org/public/mingus/src/mingus-0.29.el
VERSION = 0.29
NAME = mingus
PASDEF = mingus.pasdef
FILE = mingus.el
FETCHFILE = mingus-0.29.el
DESCRIPTION = Package for mingus (v. 0.29)

include ../generic-single.mk
include ../launchpad.mk

