URL		= http://www.emacswiki.org/cgi-bin/emacs/download/tree-mode.el
VERSION		= 1.0
NAME		= tree-mode
PASDEF		= tree-mode.pasdef
FILE		= tree-mode.el
FETCHFILE	= tree-mode.el

include ../generic-single.mk
include ../generic-e6h.mk
