URL = http://www.emacswiki.org/cgi-bin/wiki/download/dropdown-list.el
VERSION = 20090814
NAME = dropdown-list
PASDEF = dropdown-list.pasdef
FILE = dropdown-list.el
FETCHFILE = dropdown-list.el

include ../generic-single.mk
include ../generic-e6h.mk
