URL = http://www.emacswiki.org/cgi-bin/wiki/download/java-mode-indent-annotations.el
VERSION = 20060222
NAME = java-mode-indent-annotations
PASDEF = java-mode-indent-annotations.pasdef
FILE = java-mode-indent-annotations.el
FETCHFILE = java-mode-indent-annotations.el
DESCRIPTION = Package for java-mode-indent-annotations (20060222)

include ../generic-single.mk
include ../launchpad.mk
