GITURL = http://github.com/wanderlust/apel.git
NAME = apel
VERSION=10.8
PASDEF = apel.pasdef
FILES = build/*.el build/ChangeLog build/README.*
DESCRIPTION = Package for $NAME ($VERSION).

include ../generic-git.mk
include ../launchpad.mk
