GITURL		= http://github.com/wanderlust/apel.git
TAG		= 7b8ea705c53616141d7c26faf06411866709203a
NAME		= apel
VERSION		= 10.8
PASDEF		= apel.pasdef
FILES		= *.el ChangeLog README.*
DESCRIPTION	= Package for $NAME ($VERSION).

include ../generic-git.mk
include ../launchpad.mk
