NAME    = auto-complete
VERSION = 1.3
URL	= http://cx4a.org/pub/auto-complete/auto-complete-1.3.tar.bz2
PASDEF  = auto-complete.pasdef
TARFILE = auto-complete-1.3.tar.bz2
FILES   = *.el \
etc/test.txt \
README.txt \
TODO.txt \
dict/* \
doc/*

include ../generic-tarbz2.mk