GITURL		= http://github.com/wanderlust/wanderlust.git
NAME		= wl
VERSION		= 2.15.9
TAG		= wl-2_15_9
PASDEF		= wl.pasdef
FILES		= \
build/BUGS \
build/BUGS.* \
build/COPYING \
build/ChangeLog \
build/NEWS \
build/NEWS.* \
build/README \
build/README.* \
build/doc/* \
build/elmo/*.el \
build/elmo/ChangeLog \
build/etc/* \
build/etc/icons/* \
build/samples/* \
build/tests/* \
build/utils/*.el \
build/utils/ChangeLog \
build/wl/*.el \
build/wl/ChangeLog

DESCRIPTION	= Package for $NAME ($VERSION).

include ../generic-git.mk
include ../launchpad.mk
