BZRURL = http://archives.hodique.info/bzr/icicles/
NAME = icicles
PASDEF = icicles.pasdef
ELFILES = \
builddir/icicles-cmd.el \
builddir/icicles.el \
builddir/icicles-face.el \
builddir/icicles-fn.el \
builddir/icicles-mac.el \
builddir/icicles-mcmd.el \
builddir/icicles-menu.el \
builddir/icicles-mode.el \
builddir/icicles-opt.el \
builddir/icicles-var.el \
builddir/icomplete+.el

DOCFILES = 
MISCFILES = 

FILES = $(ELFILES) $(DOCFILES) $(MISCFILES)

include ../generic-bzr.mk

$(FILES): builddir
