BZRURL	= http://archives.hodique.info/bzr/icicles/
NAME	= icicles
PASDEF	= icicles.pasdef
FILES   = \
icicles-cmd.el \
icicles.el \
icicles-face.el \
icicles-fn.el \
icicles-mac.el \
icicles-mcmd.el \
icicles-menu.el \
icicles-mode.el \
icicles-opt.el \
icicles-var.el \
icomplete+.el


include ../generic-bzr.mk

$(FILES): builddir
