SVNURL = https://svn.musicpd.org/libmpdee/trunk/
VERSION = 2.1
NAME = libmpdee
PASDEF = libmpdee.pasdef
FILES = build/libmpdee.el
DESCRIPTION = Package for libmpdee (v. 2.1)

include ../generic-svn.mk
include ../launchpad.mk